<a href="https://colab.research.google.com/github/Zaheer-Aswath/DataScience-Python/blob/main/Edureka/mohammed_zaheer_day20_diy_solution_doc.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Q1. Problem Statement: Measures of Dispersion**

Load the “HRdataset_v14.csv” dataset into a DataFrame and group the data based on the “Department” column. From the grouped DataFrame and perform the following tasks:

1. Calculate the Mean and Median, of the “Salary” column.

2. Find out which Department has the highest number of employees

3. Calculate the standard deviation and variance of the “Salary” column

4. Find the interquartile range of the "Salary" column

5. Find skewness and kurtosis of the original dataset

6. Find the z-score of the "Salary" column

7. Find the 30th percentile of the "Salary" column

8. Find the Quartiles of the "GenderID" column (You can set quartile values of your choice)

In [ ]:
import pandas as pd
import numpy as np
import statistics as st
from scipy.stats import iqr
from scipy.stats import zscore


df = pd.read_csv("HRDataset_v14.csv")
#display(df)
#df.describe()

##group the data based on the “Department” column. From the grouped DataFrame and perform the following tasks:

dept_df=df.groupby("Department",as_index=False) #as_index=False there is no index, only columns
#display(dept_df.first())

##1. Calculate the Mean and Median, of the “Salary” column:

print("\n1. Calculate the Mean and Median, of the “Salary” column\n")
print("\n1.1 Mean of the “Salary” column\n")
mean_salary = dept_df["Salary"].mean()
display(mean_salary)
print("\n1.2 Median of the “Salary” column\n")
median_salary = dept_df["Salary"].median()
display(median_salary)

##2. Find out which Department has the highest number of employees:
max_dept_sal_df =  df["Department"].mode()
print("\n2. Find out which Department has the highest number of employees\n")
print("\nThis department has highest number of employees\n" ,max_dept_sal_df)

##Calculate the standard deviation and variance of the “Salary” column:

print("\n3. Calculate the standard deviation and variance of the “Salary” column\n")

#Standard Deviation:
#-->dep_sal_df=dept_df["Salary"].mean()
dep_sal_df=dept_df["Salary"].median()

print("\nDepartment-wise Standard deviation of salary: \n",dep_sal_df["Salary"].std())

#Variance from salary:
#dep_sal_df=dept_df["Salary"].mean()
#dep_sal_df=dept_df["Salary"].median()

print("\nDepartment-wise Variance of salary: \n",dep_sal_df["Salary"].var())

##4. Find the interquartile range of the "Salary" column:

print("\n4. Find the interquartile range of the “Salary” column")

print("\nInterquartile range of salary: \n",iqr(dep_sal_df["Salary"]))

##5. Find skewness and kurtosis of the original dataset:

print("\n5. Find skewness and kurtosis of the original dataset")

print("\nSkewness from original dataset: \n",df.skew())
print("\nKurtosis from original dataset: \n",df.kurt())

##6. Finding the z-score of the "Salary" column:
print("\n6. Finding the z-score of the Salary column")

standard_score = zscore(dep_sal_df["Salary"])
print("\nz-score of the Salary column(from Department)",np.array(standard_score))

##7. Finding the 30th percentile of the "Salary" column
print("\n7. Finding the the 30th percentile of the Salary column")
prtl=np.percentile(df["Salary"],30)
print("\n30th percentile of the Salary column",prtl)

##8.Finding Quartiles of the "GenderID" column:
print("\n8. Finding Quartiles of the GenderID column")
gen_qte=np.quantile([20,40],df["GenderID"])
print("\nQuartile values of 20,40 from Gender ID column:\n",gen_qte)

1. Calculate the Mean and Median, of the “Salary” column


1.1 Mean of the “Salary” column

             Department         Salary
0         Admin Offices   71791.888889
1      Executive Office  250000.000000
2                 IT/IS   97064.640000
3     Production          59953.545455
4                 Sales   69061.258065
5  Software Engineering   94989.454545

1.2 Median of the “Salary” column

             Department    Salary
0         Admin Offices   63003.0
1      Executive Office  250000.0
2                 IT/IS   92328.5
3     Production          59472.0
4                 Sales   65310.0
5  Software Engineering   95660.0

2. Find out which Department has the highest number of employees


This department has highest number of employees
 0    Production
Name: Department, dtype: object

3. Calculate the standard deviation and variance of the “Salary” column


Department-wise Standard deviation of salary:
 73050.21312523098

Department-wise Variance of salary:
 5336333637.641668

4. Find the interquartile range of the “Salary” column

Interquartile range of salary:
 31247.375

5. Find skewness and kurtosis of the original dataset

Skewness from original dataset:
 EmpID                     0.000000
MarriedID                 0.415730
MaritalStatusID           1.408602
GenderID                  0.267278
EmpStatusID               0.631944
DeptID                   -1.536392
PerfScoreID              -1.248091
FromDiversityJobFairID    2.811250
Salary                    3.306181
Termd                     0.705404
PositionID               -1.231676
Zip                       4.105494
ManagerID                 0.759271
EngagementSurvey         -1.116979
EmpSatisfaction          -0.222609
SpecialProjectsCount      1.539271
DaysLateLast30            3.143468
Absences                  0.029283
dtype: float64

Kurtosis from original dataset:
 EmpID                     -1.200000
MarriedID                 -1.839037
MaritalStatusID            2.053512
GenderID                  -1.941087
EmpStatusID               -1.488610
DeptID                     2.241434
PerfScoreID                4.049610
FromDiversityJobFairID     5.941296
Salary                    15.452149
Termd                     -1.512171
PositionID                 0.812346
Zip                       16.187425
ManagerID                  1.608422
EngagementSurvey           1.164560
EmpSatisfaction           -0.762600
SpecialProjectsCount       0.641415
DaysLateLast30             8.830523
Absences                  -1.301962
dtype: float64

6. Finding the z-score of the Salary column

z-score of the Salary column(from Department) [-0.6192146   2.18495176 -0.17945578 -0.67216471 -0.58461933 -0.12949733]

7. Finding the the 30th percentile of the Salary column

30th percentile of the Salary column 57748.0

8. Finding Quartiles of the GenderID column

Quartile values of 20,40 from Gender ID column:
 [40 40 20 20 20 20 20 40 20 40 20 40 40 40 40 40 20 20 20 40 40 20 20 20
 20 40 20 40 20 20 40 20 20 20 40 40 40 20 40 20 20 20 40 20 40 40 20 20
 40 20 40 40 40 40 40 40 20 40 20 40 20 20 20 40 40 40 20 40 20 40 40 40
 20 20 20 20 40 20 20 20 20 40 40 20 40 20 20 20 20 20 40 40 20 40 20 40
 40 20 40 20 40 20 20 20 20 40 20 20 20 40 20 40 40 20 20 40 20 20 40 20
 40 40 20 40 20 20 40 20 40 20 20 20 20 20 20 20 20 40 20 20 20 20 20 40
 20 20 20 20 40 40 20 20 20 40 40 40 40 40 20 40 40 40 20 20 40 40 40 20
 20 40 20 20 20 20 20 40 20 20 20 20 20 20 20 20 40 20 20 40 40 40 40 20
 40 20 20 40 40 40 40 40 40 20 20 20 20 20 20 20 40 40 40 20 40 40 40 20
 20 20 20 20 20 40 40 20 20 40 20 40 20 40 40 40 20 20 40 40 20 40 20 20
 20 20 40 40 40 20 20 40 40 40 20 20 20 20 40 20 20 40 40 20 20 20 40 20
 20 20 20 40 40 40 20 20 40 20 40 40 20 20 20 20 40 20 40 20 40 40 20 40
 20 40 40 40 40 20 20 40 20 20 40 20 40 40 20 20 40 20 40 20 20 20 20]

<ipython-input-10-8bcdf8bc00a5>:58: FutureWarning: The default value of numeric_only in DataFrame.skew is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  print("\nSkewness from original dataset: \n",df.skew())
<ipython-input-10-8bcdf8bc00a5>:59: FutureWarning: The default value of numeric_only in DataFrame.kurt is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  print("\nKurtosis from original dataset: \n",df.kurt())